inherit_from:
  - rules/base.yml
  - rules/ruby_target.yml
  - rules/style.yml
  - rules/performance.yml
  - rules/rails.yml
  - rules/to_decide.yml
  - rules/minitest.yml

AllCops:
  NewCops: disable
