name: Publish RubyGem

on:
  create:
      tags:
      - v*

jobs:
  publish_rubygems:
    name: Build + Publish on RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to RubyGems
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEM_API_KEY}}
